# Generated by Django 5.1.4 on 2025-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
