# Generated by Django 5.1.4 on 2025-02-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
