# Generated by Django 5.1.4 on 2025-01-17 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the news', max_length=255)),
                ('content', models.TextField(help_text='Detailed content of the news')),
                ('image', models.ImageField(blank=True, help_text='Optional image related to the news', null=True, upload_to='news/images/')),
                ('video', models.FileField(blank=True, help_text='Optional video related to the news', null=True, upload_to='news/videos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the news was created')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
