# Generated by Django 5.1.4 on 2025-01-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, help_text='Optional document (PDF, DOCX, etc.) related to the news', null=True, upload_to='news/documents/'),
        ),
    ]
