# Generated by Django 5.1.4 on 2025-01-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='document',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of media (image, video, or document)', max_length=10)),
                ('file', models.FileField(help_text='Upload an image, video, or document', upload_to='news/media/')),
                ('news', models.ForeignKey(help_text='News post associated with this media', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news')),
            ],
        ),
    ]
