# Generated by Django 5.1.4 on 2025-01-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_document_remove_news_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of media', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='news',
            field=models.ForeignKey(help_text='Associated news post', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news'),
        ),
    ]
