# Generated by Django 5.1.4 on 2025-01-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsmedia_media_type_alter_newsmedia_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bible_reference',
            field=models.TextField(blank=True, help_text='Bible reference lines related to the news', null=True),
        ),
    ]
