# Generated by Django 5.1.4 on 2025-01-18 03:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_bible_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the commenter (optional)', max_length=100, null=True)),
                ('comment_text', models.TextField(help_text='The comment content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the comment was made')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
