# Generated by Django 5.1.4 on 2025-01-18 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session or unique identifier for user', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the like was added')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.news')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('news', 'session_id')},
            },
        ),
    ]
