# Generated by Django 5.1.4 on 2025-01-30 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_churchmember_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now, help_text='The date offering was given. Displays the day of the week.')),
                ('service_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], help_text='The service during which the offering was collected.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of money collected.', max_digits=10)),
                ('mass_name', models.CharField(help_text='The name of the mass during which the offering was collected.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional details or notes about this offering.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this offering was recorded.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when this offering was last updated.')),
                ('collected_by', models.ForeignKey(help_text='The church member who collected the offering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_collected', to='members.churchmember')),
                ('recorded_by', models.ForeignKey(help_text='The church member who recorded the offering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_recorded', to='members.churchmember')),
            ],
        ),
    ]
