# Generated by Django 5.1.4 on 2025-01-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('settings', '0011_churchlocation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerings',
            name='year',
            field=models.ForeignKey(blank=True, help_text='The year in which this offering was recorded.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='settings.year'),
        ),
    ]
