# Generated by Django 5.1.4 on 2025-02-01 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_offerings_year'),
        ('members', '0009_churchmember_apostolic_movement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tithe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of tithe given in Tanzanian Shillings (TZS).', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Payment', 'Mobile Payment'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Others', 'Others')], default='Cash', help_text='Method of payment for the tithe.', max_length=20)),
                ('date_given', models.DateField(default=django.utils.timezone.now, help_text='Date when the tithe was given. Can be updated if needed.')),
                ('purpose', models.TextField(blank=True, help_text='Purpose for which the tithe was given.', null=True)),
                ('receipt_number', models.CharField(editable=False, help_text='Automatically generated receipt number (5 numbers + 5 uppercase letters).', max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the tithe was recorded.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the tithe was last updated.')),
                ('member', models.ForeignKey(help_text='The member who gave the tithe.', on_delete=django.db.models.deletion.CASCADE, related_name='tithes', to='members.churchmember')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
    ]
