# Generated by Django 5.1.4 on 2025-02-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_tithe'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithe',
            name='year',
            field=models.ForeignKey(blank=True, help_text='The year this tithe belongs to. Automatically set to the current year.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tithes', to='settings.year'),
        ),
    ]
