# Generated by Django 5.1.4 on 2025-02-01 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_tithe_year'),
        ('properties', '0002_alter_churchasset_asset_type_and_more'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentor_name', models.CharField(help_text='Name of the person renting the asset.', max_length=255)),
                ('date_rented', models.DateField(default=django.utils.timezone.now, help_text='Date when the asset was rented.')),
                ('receipt_id', models.CharField(editable=False, help_text='Automatically generated receipt ID (5 numbers + 5 uppercase letters).', max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the renting record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the renting record was last updated.')),
                ('property_rented', models.ForeignKey(help_text='The church asset that is being rented.', on_delete=django.db.models.deletion.CASCADE, related_name='facility_rentings', to='properties.churchasset')),
                ('year', models.ForeignKey(help_text='The year this renting belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='facility_rentings', to='settings.year')),
            ],
            options={
                'verbose_name': 'Facility Renting',
                'verbose_name_plural': 'Facility Rentings',
                'ordering': ['-date_rented'],
            },
        ),
    ]
