# Generated by Django 5.1.4 on 2025-02-01 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_facilityrenting'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrenting',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rental amount in Tanzanian Shillings (TZS)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
