# Generated by Django 5.1.4 on 2025-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_facilityrenting_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrenting',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose for renting the facility.', null=True),
        ),
    ]
