# Generated by Django 5.1.4 on 2025-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_facilityrenting_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrenting',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when the rental period ends.', null=True),
        ),
    ]
