# Generated by Django 5.1.4 on 2025-02-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_facilityrenting_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the special contribution (e.g., Church Renovation Fund, Charity Drive, etc.).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the purpose or details of the special contribution.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the special contribution record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the special contribution record was last updated.')),
            ],
            options={
                'verbose_name': 'Special Contribution',
                'verbose_name_plural': 'Special Contributions',
                'ordering': ['-date_created'],
            },
        ),
    ]
