# Generated by Django 5.1.4 on 2025-02-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_specialcontribution'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationItemFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='The period associated with this donation (e.g., Q1 2024, January 2024, etc.).', max_length=100)),
                ('mass_name', models.CharField(help_text='The name of the mass or event where this donation was made.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks related to the donation.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the donation item fund was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the donation item fund was last updated.')),
                ('contribution_type', models.ForeignKey(help_text='The special contribution this donation item fund belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='donation_item_funds', to='finance.specialcontribution')),
                ('year', models.ForeignKey(help_text='The year this donation item fund belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='donation_item_funds', to='settings.year')),
            ],
            options={
                'verbose_name': 'Donation Item Fund',
                'verbose_name_plural': 'Donation Item Funds',
                'ordering': ['-date_created'],
            },
        ),
    ]
