# Generated by Django 5.1.4 on 2025-02-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_donationitemfund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitemfund',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount obtained from this donation.', max_digits=12),
        ),
    ]
