# Generated by Django 5.1.4 on 2025-02-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_donationitemfund_amount'),
        ('members', '0012_merge_20250209_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promise_amount', models.DecimalField(decimal_places=2, help_text='Total amount the member has promised.', max_digits=10)),
                ('pledge_for_construction', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount pledged specifically for church construction.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the promise was made.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the promise was last updated.')),
                ('member', models.ForeignKey(help_text='The church member making the promise.', on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='members.churchmember')),
            ],
            options={
                'verbose_name': 'Promise',
                'verbose_name_plural': 'Promises',
                'ordering': ['-created_at'],
            },
        ),
    ]
