# Generated by Django 5.1.4 on 2025-02-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_promise'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=0, help_text='Month in which the promise is made.', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promise',
            name='year',
            field=models.ForeignKey(default=0, help_text='Year in which the promise is made.', on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='settings.year'),
            preserve_default=False,
        ),
    ]
