# Generated by Django 5.1.4 on 2025-02-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_promise_month_promise_year'),
        ('members', '0012_merge_20250209_0330'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_number', models.CharField(blank=True, help_text='Envelope number used for the pledge.', max_length=20, null=True)),
                ('pledge_amount', models.DecimalField(decimal_places=2, help_text='Total amount the member has pledged.', max_digits=10)),
                ('pledge_for_construction', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount specifically pledged for church construction.', max_digits=10)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Month in which the pledge is made.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the pledge was made.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the pledge was last updated.')),
                ('member', models.ForeignKey(help_text='The church member making the pledge.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='members.churchmember')),
                ('year', models.ForeignKey(help_text='Year in which the pledge is made.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='settings.year')),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Promise',
        ),
    ]
