# Generated by Django 5.1.4 on 2025-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_pledge_delete_promise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pledge_for_construction',
            field=models.DecimalField(decimal_places=2, help_text='Amount specifically pledged for church construction.', max_digits=10),
        ),
    ]
