# Generated by Django 5.1.4 on 2025-02-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_pledge_pledge_for_construction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pledge',
        ),
    ]
