# Generated by Django 5.1.4 on 2025-02-17 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_delete_pledge'),
        ('members', '0012_merge_20250209_0330'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_number', models.CharField(help_text='Envelope number used for the pledge.', max_length=50)),
                ('pledge_amount', models.DecimalField(decimal_places=2, help_text='The pledged amount.', max_digits=10)),
                ('pledge_for_construction', models.DecimalField(decimal_places=2, help_text='The amount pledged specifically for construction.', max_digits=10)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='The month in which the pledge was made.', max_length=10)),
                ('date_given', models.DateField(help_text='The date when the pledge was given.')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date and time when the pledge record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when the pledge record was last updated.')),
                ('member', models.ForeignKey(help_text='The church member making the pledge.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='members.churchmember')),
                ('year', models.ForeignKey(help_text='The year in which the pledge was made.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='settings.year')),
            ],
        ),
    ]
