# Generated by Django 5.1.4 on 2025-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('DIOCESAN', 'Special Diocesan contributions'), ('DISTRICT', 'District contributions'), ('PARISH', 'Parish contributions')], default='PARISH', help_text='Type of special contribution (Diocesan, District, or Parish).', max_length=20),
        ),
    ]
