# Generated by Django 5.1.4 on 2025-02-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_specialcontribution_contribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('DIOCESAN', 'Special Diocesan contributions'), ('REGIONAL', 'Regional contributions'), ('FELLOWSHIP', 'Fellowship contributions')], default='PARISH', help_text='Type of special contribution (Diocesan, District, or Parish).', max_length=20),
        ),
    ]
