# Generated by Django 5.1.4 on 2025-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_specialcontribution_contribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('DIOCESAN', 'Special Diocesan contributions'), ('JIMBO', 'Jimbo contributions'), ('FELLOWSHIP', 'Fellowship contributions')], default='JIMBO', help_text='Type of special contribution (Diocesan, Jimbo, or Parish).', max_length=20),
        ),
    ]
