# Generated by Django 5.1.4 on 2025-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_alter_specialcontribution_contribution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique category name (e.g., 'Construction Projects', 'Fundraising', etc.).", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description or overview of this category.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this category was first created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this category was last updated.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
