# Generated by Django 5.1.4 on 2025-02-18 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_category'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select the month for this expenditure.', max_length=15)),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the expenditure was taken (default is now).')),
                ('expenditure_amount', models.DecimalField(decimal_places=2, help_text='Amount of money spent.', max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('category', models.ForeignKey(help_text='The category under which this expenditure falls.', on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='finance.category')),
                ('year', models.ForeignKey(help_text='The year this expenditure is associated with.', on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='settings.year')),
            ],
            options={
                'verbose_name': 'Expenditure',
                'verbose_name_plural': 'Expenditures',
                'ordering': ['-date_created'],
            },
        ),
    ]
