# Generated by Django 5.1.4 on 2025-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload a receipt or supporting document for this expenditure (PDF, image, etc.).', null=True, upload_to='receipt_uploads/'),
        ),
    ]
