# Generated by Django 5.1.4 on 2025-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_expenditure_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='expenditure_purpose',
            field=models.CharField(blank=True, help_text='Brief purpose or title for this expenditure (optional).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or remarks regarding this expenditure (optional).', null=True),
        ),
    ]
