# Generated by Django 5.1.4 on 2025-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_expenditure_expenditure_purpose_expenditure_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name of the offering category (e.g., 'Sunday Mass Offering', 'Fundraising', etc.).", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details or notes about this offering category.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this offering category was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this offering category was last updated.')),
            ],
            options={
                'verbose_name': 'Offering Category',
                'verbose_name_plural': 'Offering Categories',
                'ordering': ['name'],
            },
        ),
    ]
