# Generated by Django 5.1.4 on 2025-02-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_offeringcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerings',
            name='offering_category',
            field=models.ForeignKey(default=0, help_text='Category under which this offering is classified.', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='finance.offeringcategory'),
            preserve_default=False,
        ),
    ]
