# Generated by Django 5.1.4 on 2025-04-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_offerings_offering_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tithe',
        ),
    ]
