# Generated by Django 5.2 on 2025-04-15 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_delete_tithe'),
        ('settings', '0015_delete_community_delete_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerings',
            name='outstation',
            field=models.ForeignKey(default=0, help_text='The outstation where this offering was collected.', on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='settings.outstation'),
            preserve_default=False,
        ),
    ]
