# Generated by Django 5.1.4 on 2025-02-21 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorreport',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time this report was created (set automatically).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastorreport',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this report was last updated (auto).'),
        ),
    ]
