# Generated by Django 5.1.4 on 2025-01-25 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
        ('members', '0008_churchmember_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='church_member',
            field=models.OneToOneField(blank=True, help_text='Church Member linked to this user (only required for CHURCH_MEMBER users).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='members.churchmember'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Format: +255XXXXXXXXX (9 digits after +255).', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +255XXXXXXXXX (9 digits after +255).', regex='^\\+255\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin (Superuser)'), ('CHURCH_MEMBER', 'Church Member')], default='CHURCH_MEMBER', help_text='Indicates the role this user will have in the system.', max_length=30),
        ),
    ]
