# Generated by Django 5.1.4 on 2025-02-05 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='last_visited_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
