# Generated by Django 5.1.4 on 2025-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginhistory_last_visited_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_agreed_to_terms_and_conditions',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has agreed to the terms and conditions.'),
        ),
    ]
