# Generated by Django 5.1.4 on 2025-01-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchasset',
            name='asset_type',
            field=models.CharField(choices=[('Building', 'Building'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Vehicle', 'Vehicle'), ('Stationery', 'Stationery'), ('Equipment', 'Equipment'), ('Consumables', 'Consumables')], help_text='Type of asset.', max_length=20),
        ),
        migrations.AlterField(
            model_name='churchasset',
            name='quantity_name',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Boxes', 'Boxes'), ('Packets', 'Packets'), ('Bundles', 'Bundles'), ('Sets', 'Sets'), ('Rolls', 'Rolls'), ('Pads', 'Pads'), ('Reams', 'Reams'), ('Dozens', 'Dozens'), ('Liters', 'Liters'), ('Units', 'Units'), ('Pairs', 'Pairs'), ('Square meters', 'Square meters'), ('Shelves', 'Shelves'), ('Cubic meters', 'Cubic meters'), ('Kits', 'Kits'), ('Batteries', 'Batteries'), ('Packs', 'Packs'), ('Fleets', 'Fleets'), ('Plots', 'Plots'), ('Blocks', 'Blocks'), ('Complexes', 'Complexes'), ('Towers', 'Towers'), ('Halls', 'Halls'), ('Rooms', 'Rooms'), ('Floors', 'Floors')], help_text='Unit of measurement (e.g., dozen, set, piece, etc.).', max_length=50),
        ),
    ]
