# Generated by Django 5.1.4 on 2025-01-19 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the year was added.'),
        ),
    ]
