# Generated by Django 5.1.4 on 2025-01-19 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_year_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the zone (Kanda).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the zone.', null=True)),
                ('location', models.CharField(help_text='Physical location of the zone.', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the zone was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the zone was last updated.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
