# Generated by Django 5.1.4 on 2025-01-19 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the community (Jumuiya).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the community.', null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the community was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the community was last updated.')),
                ('zone', models.ForeignKey(help_text='Zone this community belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='settings.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
