# Generated by Django 5.1.4 on 2025-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.CharField(default=0, help_text='Physical location of the community.', max_length=255),
            preserve_default=False,
        ),
    ]
