# Generated by Django 5.1.4 on 2025-01-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_community_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_id',
            field=models.PositiveIntegerField(blank=True, help_text='Randomly generated 6-digit ID for the zone.', null=True, unique=True),
        ),
    ]
