# Generated by Django 5.1.4 on 2025-01-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_zone_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_id',
            field=models.PositiveIntegerField(blank=True, help_text='7-digit unique Community ID', null=True, unique=True),
        ),
    ]
