# Generated by Django 5.1.4 on 2025-01-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_community_community_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Church latitude (Decimal degrees)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Church longitude (Decimal degrees)', max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Church altitude in meters', max_digits=7, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The last time the location was updated')),
            ],
            options={
                'verbose_name': 'Church Location',
                'verbose_name_plural': 'Church Locations',
            },
        ),
    ]
