# Generated by Django 5.1.4 on 2025-01-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_churchlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchlocation',
            options={},
        ),
        migrations.RemoveField(
            model_name='churchlocation',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='churchlocation',
            name='altitude',
            field=models.FloatField(blank=True, help_text='Altitude (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='churchlocation',
            name='latitude',
            field=models.FloatField(help_text='Latitude coordinate of the church'),
        ),
        migrations.AlterField(
            model_name='churchlocation',
            name='longitude',
            field=models.FloatField(help_text='Longitude coordinate of the church'),
        ),
    ]
