# Generated by Django 5.1.4 on 2025-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_churchlocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchlocation',
            name='altitude',
            field=models.FloatField(blank=True, help_text='Altitude (optional, will be auto-calculated if left blank)', null=True),
        ),
    ]
