# Generated by Django 5.1.4 on 2025-01-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_churchlocation_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchlocation',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark this location as the active church location'),
        ),
    ]
