# Generated by Django 5.1.4 on 2025-01-31 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_churchlocation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApostolicMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Apostolic Movement.', max_length=255, unique=True)),
                ('movement_type', models.CharField(choices=[('prayer_group', 'Prayer Group'), ('charity_organization', 'Charity Organization'), ('evangelization_group', 'Evangelization Group'), ('youth_organization', 'Youth Organization'), ('womens_group', "Women's Group"), ('mens_group', "Men's Group"), ('others', 'Others')], help_text='Type of Apostolic Movement.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of the Apostolic Movement.', null=True)),
                ('established_date', models.DateField(help_text='Date when the movement was established.')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the movement was added.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the movement was last updated.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049'), (2050, '2050'), (2051, '2051'), (2052, '2052'), (2053, '2053'), (2054, '2054'), (2055, '2055'), (2056, '2056'), (2057, '2057'), (2058, '2058'), (2059, '2059'), (2060, '2060'), (2061, '2061'), (2062, '2062'), (2063, '2063'), (2064, '2064'), (2065, '2065'), (2066, '2066'), (2067, '2067'), (2068, '2068'), (2069, '2069'), (2070, '2070'), (2071, '2071'), (2072, '2072'), (2073, '2073'), (2074, '2074'), (2075, '2075'), (2076, '2076'), (2077, '2077'), (2078, '2078'), (2079, '2079'), (2080, '2080')], help_text='Select a year from 2020 to 2080.', unique=True),
        ),
    ]
