# Generated by Django 5.1.4 on 2025-03-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApostolicMovement',
        ),
    ]
