# Generated by Django 5.1.4 on 2025-03-27 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_delete_apostolicmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstation_id', models.PositiveIntegerField(blank=True, help_text='Randomly generated 6-digit ID for the outstation.', null=True, unique=True)),
                ('name', models.CharField(help_text='Name of the outstation.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the outstation.', null=True)),
                ('location', models.CharField(help_text='Physical location of the outstation.', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the outstation was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the outstation was last updated.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='community',
            name='zone',
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.PositiveIntegerField(blank=True, help_text='7-digit unique Cell ID', null=True, unique=True)),
                ('name', models.CharField(help_text='Name of the cell.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the cell.', null=True)),
                ('location', models.CharField(help_text='Physical location of the cell.', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the cell was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the cell was last updated.')),
                ('outstation', models.ForeignKey(help_text='Outstation this cell belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='settings.outstation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
