# Generated by Django 5.1.4 on 2025-03-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_churchmember_cell'),
        ('settings', '0014_outstation_remove_community_zone_cell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
