# Generated by Django 5.2 on 2025-04-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0033_offerings_outstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvangelistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_count', models.PositiveIntegerField(help_text='Number of children who attended the worship service.')),
                ('adults_count', models.PositiveIntegerField(help_text='Number of adults who attended the worship service.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this evangelist report was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this evangelist report was last updated.')),
                ('offering', models.ForeignKey(help_text='Offering record associated with this worship service.', on_delete=django.db.models.deletion.CASCADE, related_name='evangelist_reports', to='finance.offerings')),
            ],
            options={
                'verbose_name': 'Evangelist Report',
                'verbose_name_plural': 'Evangelist Reports',
                'ordering': ['-date_created'],
            },
        ),
    ]
