# Generated by Django 5.2 on 2025-04-16 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelist', '0001_initial'),
        ('leaders', '0010_alter_leader_church_member_alter_leader_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evangelistreport',
            options={'ordering': ['-date_given'], 'verbose_name': 'Evangelist Report', 'verbose_name_plural': 'Evangelist Reports'},
        ),
        migrations.RemoveField(
            model_name='evangelistreport',
            name='offering',
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_100',
            field=models.PositiveIntegerField(default=0, help_text='Number of 100\xa0TZS coins.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_1000',
            field=models.PositiveIntegerField(default=0, help_text='Number of 1,000\xa0TZS notes.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_10000',
            field=models.PositiveIntegerField(default=0, help_text='Number of 10,000\xa0TZS notes.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_200',
            field=models.PositiveIntegerField(default=0, help_text='Number of 200\xa0TZS coins.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_2000',
            field=models.PositiveIntegerField(default=0, help_text='Number of 2,000\xa0TZS notes.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_50',
            field=models.PositiveIntegerField(default=0, help_text='Number of 50\xa0TZS coins.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_500',
            field=models.PositiveIntegerField(default=0, help_text='Number of 500\xa0TZS coins.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='count_5000',
            field=models.PositiveIntegerField(default=0, help_text='Number of 5,000\xa0TZS notes.'),
        ),
        migrations.AddField(
            model_name='evangelistreport',
            name='date_given',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the offering was given (defaults to today).'),
        ),
        migrations.AlterField(
            model_name='evangelistreport',
            name='adults_count',
            field=models.PositiveIntegerField(help_text='Number of adults present.'),
        ),
        migrations.AlterField(
            model_name='evangelistreport',
            name='children_count',
            field=models.PositiveIntegerField(help_text='Number of children present.'),
        ),
        migrations.AlterField(
            model_name='evangelistreport',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evangelistreport',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ElderDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('elder', models.ForeignKey(help_text='Select an elder who was on duty.', limit_choices_to={'occupation': 'Elder'}, on_delete=django.db.models.deletion.PROTECT, related_name='elder_duties', to='leaders.leader')),
                ('evangelist_report', models.ForeignKey(help_text='The evangelist report this duty record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='elder_duties', to='evangelist.evangelistreport')),
            ],
            options={
                'verbose_name': 'Elder on Duty',
                'verbose_name_plural': 'Elders on Duty',
                'unique_together': {('evangelist_report', 'elder')},
            },
        ),
    ]
