# Generated by Django 5.1.4 on 2025-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='association',
            field=models.CharField(default=0, help_text='Association the leader is part of within the church.', max_length=255),
            preserve_default=False,
        ),
    ]
