# Generated by Django 5.1.4 on 2025-01-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0002_leader_association'),
        ('members', '0002_remove_churchmember_denomination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='address',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='association',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='special_interests',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='talent',
        ),
        migrations.AddField(
            model_name='leader',
            name='church_member',
            field=models.OneToOneField(default=0, help_text='Select the church member who is a leader.', on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='members.churchmember'),
            preserve_default=False,
        ),
    ]
