# Generated by Django 5.1.4 on 2025-01-21 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0003_remove_leader_address_remove_leader_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time when the leader record was created.'),
        ),
    ]
