# Generated by Django 5.1.4 on 2025-01-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0004_leader_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='leader_id',
            field=models.CharField(blank=True, help_text='Unique 20-character ID with 10 digits and 10 lowercase letters.', max_length=20, null=True, unique=True),
        ),
    ]
