# Generated by Django 5.1.4 on 2025-02-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0005_leader_leader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='occupation',
            field=models.CharField(choices=[('Parish Priest', 'Parish Priest'), ('Associate Priest', 'Associate Priest'), ('Deacon', 'Deacon'), ('Lay Ministers', 'Lay Ministers'), ('Catechists', 'Catechists'), ('Community Group Leaders', 'Community Group Leaders'), ('Parish Elders', 'Parish Elders'), ('Parish Office Staff', 'Parish Office Staff'), ('Parish Council Member', 'Parish Council Member'), ('Social Ministry Leader', 'Social Ministry Leader'), ('Parish Council Chairperson', 'Parish Council Chairperson'), ('Parish Council Secretary', 'Parish Council Secretary'), ('Parish Treasurer', 'Parish Treasurer'), ('Finance Committee Member', 'Finance Committee Member'), ('Development Committee Leader', 'Development Committee Leader'), ('Choir Leader', 'Choir Leader'), ('Parish Accountant', 'Parish Accountant'), ('Religious Education Leaders', 'Religious Education Leaders'), ('Hospitality Committee Chairperson', 'Hospitality Committee Chairperson'), ('Retreat and Training Committee Member', 'Retreat and Training Committee Member'), ('Youth Committee Members', 'Youth Committee Members'), ("Women's and Men's Committee Members", "Women's and Men's Committee Members"), ('Senior Pastor', 'Senior Pastor'), ('Evangelist', 'Evangelist')], help_text='Occupation within the church.', max_length=100),
        ),
    ]
