# Generated by Django 5.1.4 on 2025-03-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0006_alter_leader_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='compensation_allowance',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='religious_education',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='voluntary',
        ),
    ]
