# Generated by Django 5.2 on 2025-04-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0007_remove_leader_committee_and_more'),
        ('settings', '0015_delete_community_delete_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='outstation',
            field=models.ForeignKey(blank=True, help_text='Outstation assignment (required for Evangelists, optional otherwise).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.outstation'),
        ),
    ]
