# Generated by Django 5.2 on 2025-04-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0008_leader_outstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='occupation',
            field=models.CharField(choices=[('Deacon', 'Deacon'), ('Evangelist', 'Evangelist'), ('Senior Pastor', 'Senior Pastor'), ('Community Group Leaders', 'Community Group Leaders'), ('Parish Elders', 'Parish Elders'), ('Choir Leader', 'Choir Leader'), ('Youth Committee Members', 'Youth Committee Members'), ("Women's and Men's Committee Members", "Women's and Men's Committee Members"), ('Religious Education Leaders', 'Religious Education Leaders'), ('Social Ministry Leader', 'Social Ministry Leader'), ('Parish Treasurer', 'Parish Treasurer'), ('Parish Accountant', 'Parish Accountant')], help_text='Occupation within the church.', max_length=100),
        ),
    ]
