# Generated by Django 5.2 on 2025-04-16 03:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0009_alter_leader_occupation'),
        ('members', '0019_alter_churchmember_address_and_more'),
        ('settings', '0015_delete_community_delete_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='church_member',
            field=models.OneToOneField(help_text='Select the church member who serves as a leader.', on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='members.churchmember'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leader_id',
            field=models.CharField(blank=True, help_text='Unique 20‑character ID with 10 digits + 10 lowercase letters.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='occupation',
            field=models.CharField(choices=[('Senior Pastor', 'Senior Pastor'), ('Associate Pastor', 'Associate Pastor'), ('Assistant Pastor', 'Assistant Pastor'), ('Youth Pastor', 'Youth Pastor'), ('Children’s Pastor', 'Children’s Pastor'), ('Evangelist', 'Evangelist'), ('Missionary', 'Missionary'), ('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Secretary', 'Secretary'), ('Assistant Secretary', 'Assistant Secretary'), ('Board Chair', 'Board Chair'), ('Board Secretary', 'Board Secretary'), ('Elder', 'Elder'), ('Chief Elder', 'Chief Elder'), ('Deacon', 'Deacon'), ('Deaconess', 'Deaconess'), ('Steward', 'Steward'), ('Worship Leader', 'Worship Leader'), ('Choir Director', 'Choir Director'), ('Praise Team Leader', 'Praise Team Leader'), ('Sunday School Teacher', 'Sunday School Teacher'), ('Bible Study Leader', 'Bible Study Leader'), ('Small Group Leader', 'Small Group Leader'), ('Youth Coordinator', 'Youth Coordinator'), ('Women’s Ministry Leader', 'Women’s Ministry Leader'), ('Men’s Ministry Leader', 'Men’s Ministry Leader'), ('Prayer Coordinator', 'Prayer Coordinator'), ('Intercessory Leader', 'Intercessory Leader'), ('Outreach Coordinator', 'Outreach Coordinator'), ('Missions Coordinator', 'Missions Coordinator'), ('Social Ministry Leader', 'Social Ministry Leader'), ('Hospitality Coordinator', 'Hospitality Coordinator'), ('Ushering Coordinator', 'Ushering Coordinator'), ('Security Coordinator', 'Security Coordinator'), ('Maintenance Supervisor', 'Maintenance Supervisor'), ('Welfare Coordinator', 'Welfare Coordinator'), ('Media/Tech Team Lead', 'Media/Tech Team Lead'), ('Communications Officer', 'Communications Officer'), ('Church Treasurer', 'Church Treasurer'), ('Church Accountant', 'Church Accountant'), ('Administrator', 'Administrator'), ('Patron', 'Patron'), ('Matron', 'Matron'), ('Advisor', 'Advisor')], help_text='Role / office held within the church.', max_length=100),
        ),
        migrations.AlterField(
            model_name='leader',
            name='outstation',
            field=models.ForeignKey(blank=True, help_text='Out‑station assignment (required for Evangelists).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.outstation'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='responsibilities',
            field=models.TextField(help_text='Key duties and ministry scope.'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='start_date',
            field=models.DateField(help_text='Date this leader began serving.'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='time_in_service',
            field=models.CharField(blank=True, help_text="Human‑readable duration in service (e.g., '3\xa0years').", max_length=100, null=True),
        ),
    ]
