# Generated by Django 5.1.4 on 2025-01-15 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the church member.', max_length=255)),
                ('date_of_birth', models.DateField(help_text='Date of birth.')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender of the church member.', max_length=10)),
                ('phone_number', models.CharField(help_text='Phone number in the format: 255XXXXXXXXX.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 255XXXXXXXXX (9 digits after 255).', regex='^255\\d{9}$')])),
                ('email', models.EmailField(blank=True, help_text="Email address (must end with '@gmail.com').", max_length=254, null=True, validators=[django.core.validators.RegexValidator(message="Email must be a valid Gmail address and end with '@gmail.com'.", regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')])),
                ('address', models.TextField(help_text='Full address of the church member.')),
                ('date_of_baptism', models.DateField(help_text='Date of baptism.')),
                ('services', models.TextField(help_text='Services the member belongs to.')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], help_text='Marital status of the church member.', max_length=20)),
                ('spouse_name', models.CharField(blank=True, help_text='Name of the person the member is married to (if applicable).', max_length=255, null=True)),
                ('number_of_children', models.CharField(blank=True, help_text='Number of children (if applicable).', max_length=10, null=True)),
                ('job', models.CharField(help_text='Job or profession of the member.', max_length=255)),
                ('talent', models.CharField(blank=True, help_text='Talent of the member (if applicable).', max_length=255, null=True)),
                ('denomination', models.CharField(help_text='Denomination of the church member.', max_length=255)),
                ('emergency_contact_name', models.CharField(help_text='Name of the person to contact during an emergency.', max_length=255)),
                ('emergency_contact_phone', models.CharField(help_text='Phone number of the emergency contact (format: 255XXXXXXXXX).', max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 255XXXXXXXXX (9 digits after 255).', regex='^255\\d{9}$')])),
                ('disability', models.TextField(blank=True, help_text='Any disability the church member has (if applicable).', null=True)),
                ('special_interests', models.TextField(blank=True, help_text='Special interests of the church member (if applicable).', null=True)),
                ('passport', models.ImageField(blank=True, help_text='Upload the passport photo of the member.', null=True, upload_to='church_member_passports/')),
            ],
        ),
    ]
