# Generated by Django 5.1.4 on 2025-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchmember',
            name='denomination',
        ),
        migrations.AddField(
            model_name='churchmember',
            name='association',
            field=models.CharField(default=0, help_text='Association of the church member.', max_length=255),
            preserve_default=False,
        ),
    ]
