# Generated by Django 5.1.4 on 2025-01-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_churchmember_denomination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchmember',
            name='services',
        ),
        migrations.AddField(
            model_name='churchmember',
            name='baptism_certificate',
            field=models.FileField(blank=True, help_text='Upload baptism certificate or document.', null=True, upload_to='baptism_certificates/'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='communion_certificate',
            field=models.FileField(blank=True, help_text='Upload First Communion certificate or document.', null=True, upload_to='communion_certificates/'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='confirmation_certificate',
            field=models.FileField(blank=True, help_text='Upload Confirmation certificate or document.', null=True, upload_to='confirmation_certificates/'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='date_confirmed',
            field=models.DateField(blank=True, help_text='Date of confirmation (if confirmed).', null=True),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='date_of_communion',
            field=models.DateField(blank=True, help_text='Date of First Communion (if received).', null=True),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='date_of_marriage',
            field=models.DateField(blank=True, help_text='Date of marriage (if married).', null=True),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='has_received_first_communion',
            field=models.BooleanField(default=False, help_text='Has the member received First Communion?'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='is_baptised',
            field=models.BooleanField(default=False, help_text='Has the member been baptized?'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Has the member been confirmed?'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='is_married',
            field=models.BooleanField(default=False, help_text='Is the member married?'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='marriage_certificate',
            field=models.FileField(blank=True, help_text='Upload Marriage certificate or document.', null=True, upload_to='marriage_certificates/'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='member_id',
            field=models.CharField(blank=True, help_text='Unique ID consisting of 3 letters and 3 numbers.', max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_of_baptism',
            field=models.DateField(blank=True, help_text='Date of baptism (if baptized).', null=True),
        ),
    ]
