# Generated by Django 5.1.4 on 2025-01-19 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_churchmember_services_and_more'),
        ('settings', '0007_community_community_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchmember',
            name='association',
        ),
        migrations.AddField(
            model_name='churchmember',
            name='community',
            field=models.ForeignKey(blank=True, help_text='The community (Jumuiya) this church member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='settings.community'),
        ),
    ]
