# Generated by Django 5.1.4 on 2025-01-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_churchmember_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Indicates whether the church member is active or inactive.', max_length=10),
        ),
    ]
