# Generated by Django 5.1.4 on 2025-01-20 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_churchmember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time when the member was created.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='member_id',
            field=models.CharField(blank=True, help_text='Unique ID consisting of 10 letters and 10 numbers.', max_length=20, null=True, unique=True),
        ),
    ]
