# Generated by Django 5.1.4 on 2025-01-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_churchmember_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='member_id',
            field=models.CharField(blank=True, help_text='Unique ID consisting of a highly randomized mix of 10 letters and 10 numbers.', max_length=20, null=True, unique=True),
        ),
    ]
