# Generated by Django 5.1.4 on 2025-01-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_churchmember_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='services',
            field=models.CharField(blank=True, help_text='Church services or ministries the member is involved in (e.g., Choir, Sunday School teacher).', max_length=255, null=True),
        ),
    ]
