# Generated by Django 5.1.4 on 2025-02-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_churchmember_services'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='apostolic_movement',
            field=models.ForeignKey(blank=True, help_text='The apostolic movement this church member is part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='settings.apostolicmovement'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='is_the_member_a_leader_of_the_movement',
            field=models.BooleanField(default=False, help_text='Is the member a leader of the apostolic movement?'),
        ),
    ]
