# Generated by Django 5.1.4 on 2025-02-09 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_churchmember_apostolic_movement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='emergency_contact_phone',
            field=models.CharField(help_text='Phone number of the emergency contact (format: 255XXXXXXXXX).', max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 255XXXXXXXXX (9 digits after 255).', regex='^255\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='phone_number',
            field=models.CharField(help_text='Phone number in the format: 255XXXXXXXXX.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 255XXXXXXXXX (9 digits after 255).', regex='^255\\d{9}$')]),
        ),
    ]
