# Generated by Django 5.1.4 on 2025-02-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_churchmember_emergency_contact_phone_and_more'),
        ('members', '0011_update_phone_numbers'),
    ]

    operations = [
    ]
