# Generated by Django 5.1.4 on 2025-03-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_merge_20250209_0330'),
        ('settings', '0012_apostolicmovement_alter_year_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchmember',
            name='apostolic_movement',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='communion_certificate',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='community',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='date_of_communion',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='has_received_first_communion',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='is_married',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='is_the_member_a_leader_of_the_movement',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='job',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='marriage_certificate',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='services',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='special_interests',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='talent',
        ),
        migrations.AddField(
            model_name='churchmember',
            name='cell',
            field=models.ForeignKey(blank=True, help_text='The cell (Jumuiya) this church member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='settings.community'),
        ),
    ]
