# Generated by Django 5.1.4 on 2025-03-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_churchmember_apostolic_movement_and_more'),
        ('settings', '0014_outstation_remove_community_zone_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='cell',
            field=models.ForeignKey(blank=True, help_text='The cell this church member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='settings.cell'),
        ),
    ]
