# Generated by Django 5.1.4 on 2025-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_churchmember_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Pending', help_text='Indicates whether the church member is active, inactive, or pending.', max_length=10),
        ),
    ]
