# Generated by Django 5.1.4 on 2025-03-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_churchmember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Has the member been confirmed?'),
        ),
    ]
