# Generated by Django 5.1.4 on 2025-03-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_churchmember_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='is_this_church_member_a_leader',
            field=models.BooleanField(default=False, help_text='Indicates whether this church member is a leader.'),
        ),
    ]
