# Generated by Django 5.2 on 2025-04-14 22:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_churchmember_is_this_church_member_a_leader'),
        ('settings', '0015_delete_community_delete_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='address',
            field=models.TextField(help_text='Anwani kamili ya mwanachama.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='baptism_certificate',
            field=models.FileField(blank=True, help_text='Pakia cheti cha ubatizo.', null=True, upload_to='baptism_certificates/'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='cell',
            field=models.ForeignKey(blank=True, help_text='Kikundi (cell) ambacho mwanachama an belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='settings.cell'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='confirmation_certificate',
            field=models.FileField(blank=True, help_text='Pakia cheti cha uthibitisho.', null=True, upload_to='confirmation_certificates/'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_confirmed',
            field=models.DateField(blank=True, help_text='Tarehe ya kuthibitishwa (kama imethibitishwa).', null=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Tarehe na muda mwanachama aliposajiliwa.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_of_baptism',
            field=models.DateField(blank=True, help_text='Tarehe ya ubatizo (kama amebatizwa).', null=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_of_birth',
            field=models.DateField(help_text='Tarehe ya kuzaliwa.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_of_marriage',
            field=models.DateField(blank=True, help_text='Tarehe ya ndoa (kama ameoa/ameolewa).', null=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='email',
            field=models.EmailField(blank=True, help_text="Anwani ya barua pepe (lazima iishie '@gmail.com').", max_length=254, null=True, validators=[django.core.validators.RegexValidator(message="Barua pepe lazima iwe anwani halali ya Gmail inayoishia '@gmail.com'.", regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')]),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='emergency_contact_name',
            field=models.CharField(help_text='Jina la mtu wa dharura.', max_length=255),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='emergency_contact_phone',
            field=models.CharField(help_text='Namba ya simu ya dharura (muundo: 255XXXXXXXXX).', max_length=12, validators=[django.core.validators.RegexValidator(message='Namba ya simu lazima iwe katika muundo: 255XXXXXXXXX (tarakimu 9 baada ya 255).', regex='^255\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='full_name',
            field=models.CharField(help_text='Jina kamili la mwanachama.', max_length=255),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Jinsia ya mwanachama.', max_length=10),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_baptised',
            field=models.BooleanField(default=False, help_text='Je, mwanachama amebatizwa?'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Je, mwanachama amethibitishwa?'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_this_church_member_a_leader',
            field=models.BooleanField(default=False, help_text='Je, mwanachama huyu ni kiongozi?'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], help_text='Hali ya ndoa ya mwanachama.', max_length=20),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='member_id',
            field=models.CharField(blank=True, help_text='Namba ya kipekee yenye mchanganyiko wa herufi 10 na tarakimu 10.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='passport',
            field=models.ImageField(blank=True, help_text='Pakia picha ya pasipoti ya mwanachama.', null=True, upload_to='church_member_passports/'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='phone_number',
            field=models.CharField(help_text='Namba ya simu katika muundo: 255XXXXXXXXX.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Namba ya simu lazima iwe katika muundo: 255XXXXXXXXX (tarakimu 9 baada ya 255).', regex='^255\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Pending', help_text='Inaonyesha hali ya uanachama (Hai, Si Hai, Inasubiri).', max_length=10),
        ),
    ]
