# Generated by Django 5.2 on 2025-04-14 22:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_churchmember_address_and_more'),
        ('settings', '0015_delete_community_delete_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='address',
            field=models.TextField(help_text='Full address of the church member.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='baptism_certificate',
            field=models.FileField(blank=True, help_text='Upload baptism certificate or document.', null=True, upload_to='baptism_certificates/'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='cell',
            field=models.ForeignKey(blank=True, help_text='The cell this church member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='settings.cell'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='confirmation_certificate',
            field=models.FileField(blank=True, help_text='Upload Confirmation certificate or document.', null=True, upload_to='confirmation_certificates/'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_confirmed',
            field=models.DateField(blank=True, help_text='Date of confirmation (if confirmed).', null=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time when the member was created.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_of_baptism',
            field=models.DateField(blank=True, help_text='Date of baptism (if baptized).', null=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='date_of_marriage',
            field=models.DateField(blank=True, help_text='Date of marriage (if married).', null=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='email',
            field=models.EmailField(blank=True, help_text="Email address (must end with '@gmail.com').", max_length=254, null=True, validators=[django.core.validators.RegexValidator(message="Email must be a valid Gmail address and end with '@gmail.com'.", regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')]),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='emergency_contact_name',
            field=models.CharField(help_text='Name of the person to contact during an emergency.', max_length=255),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='emergency_contact_phone',
            field=models.CharField(help_text='Phone number of the emergency contact (format: 255XXXXXXXXX).', max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 255XXXXXXXXX (9 digits after 255).', regex='^255\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='full_name',
            field=models.CharField(help_text='Full name of the church member.', max_length=255),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender of the church member.', max_length=10),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_baptised',
            field=models.BooleanField(default=False, help_text='Has the member been baptized?'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Has the member been confirmed?'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_this_church_member_a_leader',
            field=models.BooleanField(default=False, help_text='Indicates whether this church member is a leader.'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], help_text='Marital status of the church member.', max_length=20),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='member_id',
            field=models.CharField(blank=True, help_text='Unique ID consisting of a highly randomized mix of 10 letters and 10 numbers.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='passport',
            field=models.ImageField(blank=True, help_text='Upload the passport photo of the member.', null=True, upload_to='church_member_passports/'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='phone_number',
            field=models.CharField(help_text='Phone number in the format: 255XXXXXXXXX.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 255XXXXXXXXX (9 digits after 255).', regex='^255\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Pending', help_text='Indicates whether the church member is active, inactive, or pending.', max_length=10),
        ),
    ]
