# Generated by Django 5.1.4 on 2025-01-21 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaders', '0003_remove_leader_address_remove_leader_association_and_more'),
        ('members', '0008_churchmember_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(help_text='The body/content of the notification.')),
                ('is_read', models.BooleanField(default=False, help_text='Marks the notification as read or unread.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the notification was created.')),
                ('recipients_leaders', models.ManyToManyField(blank=True, help_text='Leaders who receive this notification.', related_name='notifications_as_leader', to='leaders.leader')),
                ('recipients_members', models.ManyToManyField(blank=True, help_text='Church members who receive this notification.', related_name='notifications_as_member', to='members.churchmember')),
            ],
        ),
    ]
