# Generated by Django 5.1.4 on 2025-01-23 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0004_leader_date_created'),
        ('members', '0008_churchmember_services'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipients_leaders',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipients_members',
        ),
        migrations.AddField(
            model_name='notification',
            name='church_member',
            field=models.ForeignKey(blank=True, help_text='Church member receiving the notification. Leave blank if sending to a leader.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.churchmember'),
        ),
        migrations.AddField(
            model_name='notification',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Leader receiving the notification. Leave blank if sending to a church member.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leaders.leader'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=0, help_text='Detailed message content of the notification.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=0, help_text='Title or subject of the notification.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the notification was created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Has the notification been read?'),
        ),
    ]
