# Generated by Django 5.1.4 on 2025-01-24 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_churchmember_services'),
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='leader',
        ),
        migrations.AlterField(
            model_name='notification',
            name='church_member',
            field=models.ForeignKey(blank=True, help_text='Church member receiving the notification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.churchmember'),
        ),
    ]
