# Generated by Django 5.1.4 on 2025-01-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_churchmember_services'),
        ('notifications', '0004_alter_notification_church_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='church_member',
            field=models.ForeignKey(default=0, help_text='Church member receiving the notification. Required field.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.churchmember'),
            preserve_default=False,
        ),
    ]
